auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 永恒的心
url: http://zhoupengml.github.io
feed: /atom.xml
author_info: <a href="http://zhoupengml.github.io/">Peng Zhou</a>
